### ISSUE TITLE
CAS staff side authentication

### ISSUE THREAD

**Issue by bpalme** [kevinoconnor7/osTicket-auth-cas#8] opened 2015-11-05 15:23 UTC
We are seeing that after returning from the CAS server on the staff side we get the staff login page with authentication error message (I can tell the CAS authentication was successful from debug messages).   But if you refresh the browser, you get access.  This is on OST 10 RC2 and your plugin version is the one just prior to adding the central logout functionality.  Any ideas on whether this is a plugin thing or whether I should look elsewhere.  Thanks for your help!  

-Brent (ICPL)

**Comment by kevinoconnor7** [comment] 2015-11-05 15:56
Duplicate of #5.

It's a bug in osTicket. I don't know if they've cut a release since then but you can apply the patch in https://github.com/osTicket/osTicket-1.8/pull/2641

**Closed as completed by kevinoconnor7** 2015-11-05 15:56 UTC
Labels: duplicate

**Comment by bpalme** [comment] 2015-11-05 21:46
worked like a charm.  thanks for the quick response.
